###
GET http://localhost:3000/holdings
Content-Type: application/json

###
POST http://localhost:3000/holdings
Content-Type: application/json

{
    "ticker": "SOXL",
    "quantity": 4,
    "cost": {
        "average": 1094.14,
        "total": 4376.57
    },
    "vix": null,
    "sp500": null
}